version: '3'

services:
  db:
    image: postgres:latest
    container_name: shervn-blog_database
    volumes: 
      - ./shervn-database/db/:/var/lib/postgresql/data
    env_file:
      - .env

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
      
  backend:
    build: 
      context: ./shervn-backend/.
      args:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DB=$POSTGRES_DB
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:3000"
    depends_on:
      - db
    volumes: 
      - ./shervn-database/media/:/backend/media/
    env_file:
      - .env

  frontend:
    build: shervn-frontend/.
    # command: npm run start
    volumes:
      - ./shervn-frontend/:/frontend/
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: ./shervn-nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./shervn-database/media/:/media/
    depends_on:
      - frontend
      - backend
    links:
      - backend