version: '3'

services:
  db:
    image: postgres:latest
    container_name: shervn-blog_database
    volumes: 
      - /mnt/blog/db/:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
      
  backend:
    build: 
      context: ./shervn-backend/.
      args:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DB=$POSTGRES_DB
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && ls && pip install gunicorn && gunicorn blog.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    volumes: 
      - /mnt/blog/media/:/backend/media/
    env_file:
      - .env
    ports:
      - 8000:8000

  frontend:
    build: shervn-frontend/.
    # command: npm run start
    volumes:
      - ./shervn-frontend/:/frontend/
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: ./shervn-nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - /mnt/blog/media/:/media/
    depends_on:
      - frontend
      - backend
    links:
      - backend
