# Generated by Django 2.2.6 on 2019-11-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.CharField(max_length=50)),
                ('body', models.TextField(verbose_name='Body')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('link', models.URLField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
