# Generated by Django 2.2.6 on 2019-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcomponents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.TextField(max_length=120)),
                ('date', models.CharField(max_length=50)),
                ('className', models.CharField(default='post', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('projectLink', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundCloudPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('className', models.CharField(default='farsiPost', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('soundCloudLink', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='textpost',
            name='link',
        ),
        migrations.RemoveField(
            model_name='textpost',
            name='picture',
        ),
        migrations.AddField(
            model_name='textpost',
            name='className',
            field=models.CharField(default='farsiPost', max_length=20),
        ),
        migrations.AddField(
            model_name='textpost',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='title',
            field=models.TextField(),
        ),
    ]
