# Generated by Django 2.2.6 on 2019-11-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcomponents', '0002_auto_20191101_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundcloudpost',
            name='playlist',
            field=models.BooleanField(default=False),
        ),
    ]
