# Generated by Django 2.2.6 on 2019-11-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcomponents', '0003_soundcloudpost_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('titleLong', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('className', models.CharField(default='farsiPost', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('imageUrl', models.ImageField(upload_to='')),
                ('bandName', models.CharField(max_length=30)),
            ],
        ),
    ]
