# Generated by Django 2.2.6 on 2019-11-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcomponents', '0004_reviewpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpost',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soundcloudpost',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textpost',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewpost',
            name='imageUrl',
            field=models.ImageField(upload_to='review_images/'),
        ),
    ]
